# Generated by Django 3.0.5 on 2020-08-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_auto_20200825_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Произведения'},
        ),
    ]
